--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ-Libraries/SimpleSQL
build-by-default: true
branches:
- main
projects:
  examples.SimpleEconomy:
    path: examples/SimpleEconomy/
  SimpleSQL:
    path: ""
    model: virion
    type: library
...
