name: SimpleEconomy
main: NhanAZ\SimpleEconomy\Main
version: 1.0.1
api: 5.0.0
author: NhanAZ
description: "A simple economy plugin powered by SimpleSQL — demonstrates the Hybrid SQL-YAML pattern."

permissions:
  simpleeconomy.command.money:
    description: "View balances."
    default: true
  simpleeconomy.command.pay:
    description: "Transfer money."
    default: true
  simpleeconomy.command.setmoney:
    description: "Set a player's balance."
    default: op
